### ISSUE TITLE
Disp_i2t is not seen

### ISSUE THREAD

**Issue by YinTaiWang** [vincentme/GroupRegNet#11]
Hi Vincent, first I wanna thank you so much for sharing your work and the code.
I have however a question in the code, there are some lines calling res['disp_i2t'] but I can't find the code that stores this data and neither why is used in the paper. I wonder if you have more information that can share? Thanks in advance!

**Comment by vincentme** [comment]
Hi Wang,

res['disp_i2t'] is used to calculate the displacement between different phases. If you check model/util.py, the class CalcDisp is there for this purpose.
