### ISSUE TITLE
 The preprocessing part of data set DIR-Lab

### ISSUE THREAD

**Issue by lxy51** [vincentme/GroupRegNet#13]
First of all, thank you for your great creation. When you preprocess the data set DIR-Lab in the code. Different clipping ranges are used for different cases. For example, for case1, crop_range = [slice(0, 83), slice(43, 200), slice(10, 250)] is used. I want to know how these three ranges are derived. Is it convenient to inform. Looking forward to your reply.

**Comment by vincentme** [comment]
Oh, these crops are for computation speed purpose. The region of the lung is observed and recorded in 3dSlicer.

**Comment by lxy51** [comment]
Thank you for your answer. What you mean is. This range of values. It was recorded manually by myself after 3dSlicer observation.
