### ISSUE TITLE
how to convert original data to mhd format

### ISSUE THREAD

**Issue by LemonYear** [vincentme/GroupRegNet#2]
Excuse me! I am dealing with the DIR-Lab data, but I have got trouble in converting the original data format (.img) to mhd format. Could you tell me  the method of converting the data format? Looking forward to your reply!

**Comment by vincentme** [comment]
You are welcome. 

DIR-lab provided the matlab script to load img file. You can follow instruction there
https://www.dir-lab.com/DownLoads/SoftwareSummary/MatlabUtilityPack1.pdf

To save the image to mhd format, you can use this function
https://www.mathworks.com/matlabcentral/fileexchange/52982-matlab-elastix

**Comment by LemonYear** [comment]
Thank you for your reply! I have solved the problem by your method. Thanks very much!
