### ISSUE TITLE
How to calculate the displacement field among any image pairs

### ISSUE THREAD

**Issue by Younglll45** [vincentme/GroupRegNet#3]
Thanks for your work! Thanks for your sharing!

The output in the GroupRegNet is the displacement field from the implicit template to the input images. And in the paper, you say “The transformation mapping between the nth and mth image can be calculated using the composition of the deformation field”. But I still feel confused about how to calculate the composition field. 
For example, if I want to get the displacement filed from case1_T50 image to case1_T00 image. In conventional methods, I need to minimize the dissimilarity of warped case1_T00 image and case1_T50 image. Then I can use the displacement field to calculate the landmark TRE. But in the GroupRegNet, I get the displacement filed (flow1) from template to case1_T00 and displacement filed (flow2) from template to case1_T50. Then I use the model.util.CalcDisp(3).inverse_disp(flow2) to get the inverse flow2. And use model.util.CalcDisp(3).compose_disp(flow1, inverse flow 2) to get the composition field. But after transforming the case1_T50 image landmarks according to the composition field, the TRE is wrong. Is there something wrong when I calculate the composition field? It really matters me a lot. Could you help me? Looking forward to your reply! 

Thank you very much！

**Comment by vincentme** [comment]
You are welcome

Yes, here it is a little bit tricky. If you want to calculate the displacement disp50_00 from phase 50 to phase 00. The code is 

```
calcdisp = model.util.CalcDisp(dim = config.dim, calc_device = 'cuda')
disp_50_t = calcdisp.inverse_disp(res['disp_t2i'][5:6])
disp50_00 = calcdisp.compose_disp(disp_50_t, res['disp_t2i'][0:1], mode = 'coor')
```

So the correct way is from phase 50 to template then to phase 00. You did compose the displacement from template to phase 00 with phase 50 to the template, therefore the result is not correct. 

The following is the code snippet I use to calculate the TRE. Because it involves loading the manual landmarks, so I did not include it in the repository. But you may find it helpful. The `config.pair_disp_indexes = [0, 5]` is the phases with known landmarks. `landmark_disp` is the displacement of landmarks from phase 00 to phase 50. 

```
    if i % config.pair_disp_calc_interval == 0:
        if 'disp_i2t' in res:
            disp_i2t = res['disp_i2t'][config.pair_disp_indexes]
        else:
            disp_i2t = calcdisp.inverse_disp(res['disp_t2i'][config.pair_disp_indexes])
        composed_disp = calcdisp.compose_disp(disp_i2t, res['disp_t2i'][config.pair_disp_indexes], mode = 'all')
        composed_disp_np = composed_disp.cpu().numpy() # (2, 2, 3, d, h, w)

        inter = interpolate.RegularGridInterpolator(grid_tuple, np.moveaxis(composed_disp_np[0, 1], 0, -1))
        calc_landmark_disp = inter(landmark_00_converted)

        diff = (np.sum(((calc_landmark_disp - landmark_disp)*pixel_spacing)**2, 1))**0.5
        diff_stats.append([i, np.mean(diff), np.std(diff)])
        print(f'\ndiff: {np.mean(diff):.2f}+-{np.std(diff):.2f}({np.max(diff):.2f})')
```

**Comment by Younglll45** [comment]
Thank you for your reply!

Very very grateful for your help! Sorry to bother you again! However, I still can not  get the correct TRE although following the suggestions given. I don't know whether I use your code by mistake. The code are as following:
`#calculate the displacement field from T00 to T50
weights = torch.load(model_path)
res = weights['registration_result']
config.pair_disp_indexes = [0,5]
disp_i2t = calcdisp.inverse_disp(res['disp_t2i'][config.pair_disp_indexes])
composed_disp = calcdisp.compose_disp(disp_i2t, res['disp_t2i'][config.pair_disp_indexes], mode = 'all')
composed_disp_np = composed_disp.cpu().numpy() # (2, 2, 3, d, h, w)

# get the inter
d = np.linspace(0,composed_disp_np.shape[3]-1,composed_disp_np.shape[3])
h = np.linspace(0,composed_disp_np.shape[4]-1,composed_disp_np.shape[4])
w = np.linspace(0,composed_disp_np.shape[5]-1,composed_disp_np.shape[5])
grid_tuple = (d,h,w)
inter = interpolate.RegularGridInterpolator(grid_tuple, np.moveaxis(composed_disp_np[0, 1], 0, -1))

# get the converted case1_T00 landmark
# crop_range = [slice(0, 83), slice(43, 200), slice(10, 250)]
# change landmark format (x,y,z) to (z,y,x)
t00_lmk_convert = t00_lmk.copy()  #t00_lmk refer to the case1_T00 landmark with shape(300,3)
for i in range(t00_lmk.shape[0]):
    t00_lmk_convert[i,0] = t00_lmk_convert[i,0] - 10 #crop the index according to preprocessing
    t00_lmk_convert[i,1] = t00_lmk_convert[i,1] - 43
t00_lmk_convert_1 = t00_lmk_convert.copy()
t00_lmk_convert_1[:,[0,2]] = t00_lmk_convert_1[:,[2,0]] #change(x,y,z) to (z,y,x)
calc_landmark_disp = inter(t00_lmk_convert_1)

#calculate the landmark_disp
landmark_disp =t50_lmk - t00_lmk
diff = (np.sum(((calc_landmark_disp - landmark_disp)*spacing)**2, 1))**0.5
print(np.mean(diff))` 

the result is 2.8823. Is there something wrong when I calculate the TRE? Looking forward to your reply!

Thank you very much!

**Comment by Younglll45** [comment]
Thank you for your reply!

Very very grateful for your help! Sorry to bother you again! However, I still can not  get the correct TRE although following the suggestions given. I don't know whether I use your code by mistake. The code are as following:

- firstly, calculate the displacement field from T00 to T50

```
weights= torch.load(model_path) 
res = weights['registration_result']
config.pair_disp_indexes = [0,5]
disp_i2t = calcdisp.inverse_disp(res['disp_t2i'][config.pair_disp_indexes])
composed_disp = calcdisp.compose_disp(disp_i2t, res['disp_t2i'][config.pair_disp_indexes], mode = 'all')
composed_disp_np = composed_disp.cpu().numpy() # (2, 2, 3, d, h, w)
```

- then, get the inter

```
d = np.linspace(0,composed_disp_np.shape[3]-1,composed_disp_np.shape[3])
h = np.linspace(0,composed_disp_np.shape[4]-1,composed_disp_np.shape[4])
w = np.linspace(0,composed_disp_np.shape[5]-1,composed_disp_np.shape[5])
grid_tuple = (d,h,w)
inter = interpolate.RegularGridInterpolator(grid_tuple, np.moveaxis(composed_disp_np[0, 1], 0, -1))
```

- and get the converted case1_T00 landmark

```
t00_lmk_convert= t00_lmk.copy()  #t00_lmk refer to the case1_T00 landmark with shape(300,3)
for i in range(t00_lmk.shape[0]):
    t00_lmk_convert[i,0] = t00_lmk_convert[i,0] - 10 #crop the index according to preprocessing
    t00_lmk_convert[i,1] = t00_lmk_convert[i,1] - 43 # crop_range = [slice(0, 83), slice(43, 200), slice(10, 250)]
t00_lmk_convert_1 = t00_lmk_convert.copy()
t00_lmk_convert_1[:,[0,2]] = t00_lmk_convert_1[:,[2,0]] #change(x,y,z) to (z,y,x)
calc_landmark_disp = inter(t00_lmk_convert_1)

```
- calculate the landmark_disp and diff

```
landmark_disp =t50_lmk - t00_lmk
diff = (np.sum(((calc_landmark_disp - landmark_disp)*spacing)**2, 1))**0.5
print(np.mean(diff))
```

the result is 2.8823. Is there something wrong when I calculate the TRE? Looking forward to your reply!

Thank you very much!

**Comment by vincentme** [comment]
There are few things need to be careful. The original index provided by DIR-Lab is 1-based, e.g., the index of top-left voxel is [1, 1, 1]. It has to be converted to 0-based index to be consistent with the registration code. I have added the `convert_landmark_dirlab300.py` file for your reference. 

Second, The order of axis of the `landmark_disp` and  `calc_landmark_disp` is assumed to be [x, y, z] in the second axis, which is also true for `disp_i2t`, `disp_t2i` and so on. Here x, y, z correspond to the Width, Height, Depth of the original image respectively. So to get the correct result, it also should be consistent. 

The `registration_dirlab.py` has been modified and it should be a complete example with TRE evaluation.

**Comment by Younglll45** [comment]
Thank you for your reply! Thank you for your help!

I am sorry to reply you late. With your code newly provided, I could achieve the TRE result close to yours, but when I train case6,7,8, the loss is nan sometimes. What can I do to avoid this situation? 

Thank you very much!

**Comment by Younglll45** [comment]
Thank you for your reply! Thank you for your help!

I am sorry to reply you late. With your code newly provided, I could achieve the TRE result close to yours, but when I train case6,7,8, the loss is nan. What can I do to avoid this situation?

Thank you very much!

**Comment by vincentme** [comment]
Sorry, I have not had the issue you mentioned. With the limited information, I can only suggest you debug through the code to see which part cause the issue.

**Comment by Younglll45** [comment]
Thank you for your help! I do need some time to debug. Maybe there is something wrong when I preprocess the original data.
