### ISSUE TITLE
Implementation of cyclic loss

### ISSUE THREAD

**Issue by cs123951** [vincentme/GroupRegNet#4]
Hello,
     Thank you for sharing your code.
     I have read your paper [1], and found a sentence in the paper, 

> An optional cyclic consistent regularization loss is used if deformation fields in the
group are periodic or symmetric

    Your paper used lung CT sets which are periodic for experiments. However, in the code, I could not find anything about cyclic consistent regularization loss. Does the cyclic loss contribute to the improvement of the registration method? Have you done any contrast experiments? 

Thank you very much if you could answer my questions.
    

1. Zhang Y, Wu X, Gach HM, Li H, Yang D. GroupRegNet: A Groupwise One-shot Deep Learning-based 4D Image Registration Method. Phys Med Biol. 2021;66(4):045030. doi:10.1088/1361-6560/abd956

**Comment by vincentme** [comment]
The cyclic loss is directly implemented in the registration code
https://github.com/vincentme/GroupRegNet/blob/8ab131e0d1015bf7018533b5ab1b38de65987b21/registration_dirlab.py#L161

I used to have a comparison result, but as mentioned in the paper, the improvement is minor, so not recorded. You can test to set the cyclic_reg as a different value.

**Comment by cs123951** [comment]
Thank you! I figure it out.
