### ISSUE TITLE
 No module named 'utils.structure'

### ISSUE THREAD

**Issue by FDC-WuWeb** [vincentme/GroupRegNet#5]
Thanks for your sharing.
I have  read your paper of GroupRegNet, it's really a fantastic work. But I get a problem when learning the source code. It says that there is an module error :  "ModuleNotFoundError: No module named 'utils.structure'" in registration_dirlab.py. I have installed utils module with pip, and I have check the utils.py file which really doesn't have the structure module. Since utils.structure plays an important role in the following codes(config = utils.structure.Struct(**config),and config is everywhere in registration_dirlab.py), I'm stuck here. 
There must be something wrong with utils module, how can I fixed it, would you mind share the utils.py with me?  Thank you very much. Sorry for asking you the issue of coding,  your work and your code help me a lot, but I'm really stuck here. Hope you could answer my question.

**Comment by vincentme** [comment]
Thanks for the reminder. The structure.py file has been uploaded. Please check the latest version and let me know if there is any issue. Thanks.
